name: Linux Release
permissions:
  contents: write

on:
  push:
    tags:
      - "v*.*.*"
      - "!*-alpha*"
      - "!*-preview*"
  workflow_dispatch:
    inputs:
      name:
        description: "reason"
        required: false
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check repository URL
        run: |
          REPO_URL=$(git config --get remote.origin.url)
          if [[ $REPO_URL == *"pro" ]]; then
            exit 1
          fi
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Build Frontend
        env:
          CI: ""
        run: |
          cd web
          git describe --tags > VERSION
          REACT_APP_VERSION=$(git describe --tags)
          chmod u+x ./build.sh && ./build.sh
          cd ..
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.18.0"
      - name: Build Backend (amd64)
        run: |
          go mod download
          go build -ldflags "-s -w -extldflags '-static'" -o hixai2api

      - name: Build Backend (arm64)
        run: |
          sudo apt-get update
          sudo apt-get install gcc-aarch64-linux-gnu
          CC=aarch64-linux-gnu-gcc CGO_ENABLED=1 GOOS=linux GOARCH=arm64 go build -ldflags "-s -w -extldflags '-static'" -o hixai2api-arm64

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            hixai2api
            hixai2api-arm64
          draft: true
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
